#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
  ListPromptsRequestSchema,
  GetPromptRequestSchema,
  ListResourcesRequestSchema,
  ReadResourceRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { extractVideoId, fetchTranscript } from "./transcript.js";

const server = new Server(
  {
    name: "rippr-mcp",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
      prompts: {},
      resources: {},
    },
  }
);

// ── List available tools ────────────────────────────
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "rip_transcript",
      description:
        "Extract the full transcript from a YouTube video. Returns the video title, channel, language, and transcript text. Supports any YouTube URL format.",
      inputSchema: {
        type: "object" as const,
        properties: {
          url: {
            type: "string",
            description:
              "YouTube video URL (e.g., https://www.youtube.com/watch?v=... or https://youtu.be/...)",
          },
          format: {
            type: "string",
            enum: ["text", "segments"],
            description:
              "Output format. 'text' returns a single continuous string (best for RAG/LLM). 'segments' returns timestamped segments. Default: text.",
          },
        },
        required: ["url"],
      },
    },
  ],
}));

// ── Handle tool calls ───────────────────────────────
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name !== "rip_transcript") {
    return {
      content: [{ type: "text", text: `Unknown tool: ${request.params.name}` }],
      isError: true,
    };
  }

  const args = request.params.arguments as {
    url: string;
    format?: "text" | "segments";
  };

  const videoId = extractVideoId(args.url);
  if (!videoId) {
    return {
      content: [
        {
          type: "text",
          text: `Could not extract a YouTube video ID from: ${args.url}`,
        },
      ],
      isError: true,
    };
  }

  try {
    const result = await fetchTranscript(videoId);
    const format = args.format || "text";

    if (format === "segments") {
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                title: result.title,
                channel: result.channel,
                language: result.language,
                isAutoGenerated: result.isAuto,
                videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
                segmentCount: result.segments.length,
                segments: result.segments,
              },
              null,
              2
            ),
          },
        ],
      };
    }

    // Default: text format (optimized for LLM consumption)
    const fullText = result.segments.map((s) => s.text).join(" ");
    return {
      content: [
        {
          type: "text",
          text: [
            `Title: ${result.title}`,
            `Channel: ${result.channel}`,
            `Language: ${result.language}${result.isAuto ? " (auto-generated)" : ""}`,
            `URL: https://www.youtube.com/watch?v=${videoId}`,
            "",
            fullText,
          ].join("\n"),
        },
      ],
    };
  } catch (error: any) {
    return {
      content: [
        {
          type: "text",
          text: `Failed to extract transcript: ${error.message}`,
        },
      ],
      isError: true,
    };
  }
});

// ── Prompts ────────────────────────────────────────

server.setRequestHandler(ListPromptsRequestSchema, async () => ({
  prompts: [
    {
      name: "get_transcript",
      description: "Get the full transcript of a YouTube video",
      arguments: [
        { name: "url", description: "YouTube video URL", required: true },
      ],
    },
    {
      name: "summarize_video",
      description: "Get a YouTube video transcript and summarize the key points",
      arguments: [
        { name: "url", description: "YouTube video URL", required: true },
      ],
    },
    {
      name: "extract_quotes",
      description: "Pull notable quotes or key statements from a YouTube video",
      arguments: [
        { name: "url", description: "YouTube video URL", required: true },
        { name: "topic", description: "Topic to focus on (optional)", required: false },
      ],
    },
    {
      name: "compare_videos",
      description: "Compare the content of two YouTube videos",
      arguments: [
        { name: "url1", description: "First YouTube video URL", required: true },
        { name: "url2", description: "Second YouTube video URL", required: true },
      ],
    },
    {
      name: "research_topic",
      description: "Get a transcript and extract information relevant to a specific topic",
      arguments: [
        { name: "url", description: "YouTube video URL", required: true },
        { name: "topic", description: "Topic to research", required: true },
      ],
    },
  ],
}));

server.setRequestHandler(GetPromptRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  switch (name) {
    case "get_transcript":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: `Get the transcript of this YouTube video: ${args?.url}`,
            },
          },
        ],
      };
    case "summarize_video":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: `Get the transcript of this YouTube video and summarize the key points: ${args?.url}`,
            },
          },
        ],
      };
    case "extract_quotes":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: args?.topic
                ? `Get the transcript of this YouTube video and pull out notable quotes about "${args.topic}": ${args?.url}`
                : `Get the transcript of this YouTube video and pull out the most notable quotes: ${args?.url}`,
            },
          },
        ],
      };
    case "compare_videos":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: `Get the transcripts of these two YouTube videos and compare their content:\n1. ${args?.url1}\n2. ${args?.url2}`,
            },
          },
        ],
      };
    case "research_topic":
      return {
        messages: [
          {
            role: "user" as const,
            content: {
              type: "text" as const,
              text: `Get the transcript of this YouTube video and extract all information relevant to "${args?.topic}": ${args?.url}`,
            },
          },
        ],
      };
    default:
      throw new Error(`Unknown prompt: ${name}`);
  }
});

// ── Resources ──────────────────────────────────────

server.setRequestHandler(ListResourcesRequestSchema, async () => ({
  resources: [
    {
      uri: "rippr://formats",
      name: "Output Formats",
      description: "Available transcript output formats and when to use each one",
      mimeType: "application/json",
    },
  ],
}));

server.setRequestHandler(ReadResourceRequestSchema, async (request) => {
  if (request.params.uri === "rippr://formats") {
    return {
      contents: [
        {
          uri: "rippr://formats",
          mimeType: "application/json",
          text: JSON.stringify({
            formats: [
              {
                name: "text",
                description: "Single continuous text block. Best for LLM consumption, RAG pipelines, and summarization.",
                default: true,
              },
              {
                name: "segments",
                description: "Timestamped segments with metadata. Best for referencing specific moments, building chapter markers, or detailed analysis.",
                default: false,
              },
            ],
          }, null, 2),
        },
      ],
    };
  }
  throw new Error(`Unknown resource: ${request.params.uri}`);
});

// ── Start server ────────────────────────────────────
async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rippr-mcp server running on stdio");
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
