#!/usr/bin/env node

import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { extractVideoId, fetchTranscript } from "./transcript.js";

const server = new Server(
  {
    name: "rippr-mcp",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

// ── List available tools ────────────────────────────
server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "rip_transcript",
      description:
        "Extract the full transcript from a YouTube video. Returns the video title, channel, language, and transcript text. Supports any YouTube URL format.",
      inputSchema: {
        type: "object" as const,
        properties: {
          url: {
            type: "string",
            description:
              "YouTube video URL (e.g., https://www.youtube.com/watch?v=... or https://youtu.be/...)",
          },
          format: {
            type: "string",
            enum: ["text", "segments"],
            description:
              "Output format. 'text' returns a single continuous string (best for RAG/LLM). 'segments' returns timestamped segments. Default: text.",
          },
        },
        required: ["url"],
      },
    },
  ],
}));

// ── Handle tool calls ───────────────────────────────
server.setRequestHandler(CallToolRequestSchema, async (request) => {
  if (request.params.name !== "rip_transcript") {
    return {
      content: [{ type: "text", text: `Unknown tool: ${request.params.name}` }],
      isError: true,
    };
  }

  const args = request.params.arguments as {
    url: string;
    format?: "text" | "segments";
  };

  const videoId = extractVideoId(args.url);
  if (!videoId) {
    return {
      content: [
        {
          type: "text",
          text: `Could not extract a YouTube video ID from: ${args.url}`,
        },
      ],
      isError: true,
    };
  }

  try {
    const result = await fetchTranscript(videoId);
    const format = args.format || "text";

    if (format === "segments") {
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                title: result.title,
                channel: result.channel,
                language: result.language,
                isAutoGenerated: result.isAuto,
                videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
                segmentCount: result.segments.length,
                segments: result.segments,
              },
              null,
              2
            ),
          },
        ],
      };
    }

    // Default: text format (optimized for LLM consumption)
    const fullText = result.segments.map((s) => s.text).join(" ");
    return {
      content: [
        {
          type: "text",
          text: [
            `Title: ${result.title}`,
            `Channel: ${result.channel}`,
            `Language: ${result.language}${result.isAuto ? " (auto-generated)" : ""}`,
            `URL: https://www.youtube.com/watch?v=${videoId}`,
            "",
            fullText,
          ].join("\n"),
        },
      ],
    };
  } catch (error: any) {
    return {
      content: [
        {
          type: "text",
          text: `Failed to extract transcript: ${error.message}`,
        },
      ],
      isError: true,
    };
  }
});

// ── Start server ────────────────────────────────────
async function main(): Promise<void> {
  const transport = new StdioServerTransport();
  await server.connect(transport);
  console.error("rippr-mcp server running on stdio");
}

main().catch((error) => {
  console.error("Fatal error:", error);
  process.exit(1);
});
