name = "rippr-web"
main = "src/worker.js"
compatibility_date = "2024-09-23"

routes = [
  { pattern = "rippr.me/*", zone_name = "rippr.me" },
  { pattern = "www.rippr.me/*", zone_name = "rippr.me" },
]

[ai]
binding = "AI"

[[rules]]
type = "Text"
globs = ["**/*.html"]

[[rules]]
type = "Data"
globs = ["**/*.png"]
